[WIP] 🚀 Add NonLinearProgram Support to DiffOpt.jl
jump-dev/DiffOpt.jl pull request #260
Opened 2024-12-06 15:07 UTC by andrewrosemberg

This PR introduces a new module, `NonLinearProgram`, to extend DiffOpt.jl's functionality for differentiating nonlinear optimization problems (NLPs). The implementation integrates with JuMP-based nonlinear models and supports advanced derivative computation through custom evaluator and differentiation logic.

### 🆕 Features

- **Nonlinear Model Differentiation**:
  - Forward and reverse differentiation for user-specified primal variables (`focus_vars`) and dual variables (`focus_duals`) with respect to a given set of parameters.
  - Extensible API for handling NLP-specific sensitivities using custom utilities.

- **Core Structures**:
  - `Cache`: Stores primal variables, parameters, evaluator, and constraints for efficient reuse.
  - `ForwCache`: Holds results of forward differentiation, including sensitivities for specified variables.
  - `ReverseCache`: Holds results of reverse differentiation (implemented in this PR).

- **Integration with DiffOpt API**:
  - Implements `DiffOpt.AbstractModel` for seamless compatibility with DiffOpt's API.
  - Provides `forward_differentiate!` and `reverse_differentiate!` functions for NLPs.

### 🔧 How It Works

1. **Custom Sensitivity Calculations**:
   - Utilizes `nlp_utilities.jl` to compute derivatives of the optimization problem with respect to selected parameters.
   - Allows differentiation of only specific variables and duals, offering a fine-grained approach compared to existing DiffOpt modules.

2. **Forward Differentiation**:
   - Computes Jacobian products for selected primal and dual variables using the provided parameters.
   - Results are cached for efficient access through the DiffOpt API.

3. **Reverse Differentiation**:
   - Computes transpose Jacobian products for selected primal and dual variables with respect to the parameters.
   - Results are cached in `ReverseCache`.

### 📜 Implementation Highlights

- **Forward Differentiation**:
  ```julia
  DiffOpt.forward_differentiate!(model; focus_vars, focus_duals, params)
  ```
  - Calculates sensitivity of `focus_vars` and `focus_duals` w.r.t. `params`.
  - Results are cached in `ForwCache`.

- **Reverse Differentiation**:
  ```julia
  DiffOpt.reverse_differentiate!(model)
  ```
  - Computes transpose Jacobian products for parameters with respect to the primal and dual variables.
  - Results are cached in `ReverseCache`.

- **Custom Utilities**:
  - Leverages `create_evaluator`, `compute_sensitivity`, and other utilities from `nlp_utilities.jl` for efficient derivative computation.

### 📋 Example Usage

#### Forward Differentiation
```julia
using DiffOpt
using NonLinearProgram
using JuMP

# Define a JuMP model
model = Model()
@variable(model, x >= p)
@variable(model, y >= 0)
@objective(model, Min, x^2 + y^2)
@constraint(model, con, x + y >= 1)

# Create a DiffOpt NonLinearProgram model
nlp_model = NonLinearProgram.Model(model)

# Specify variables and parameters for differentiation
focus_vars = [x, y]
focus_duals = [con]
params = [p]

# Forward differentiation
DiffOpt.forward_differentiate!(nlp_model; focus_vars=focus_vars, focus_duals=focus_duals, params=params)

# Retrieve sensitivities
dx_dx = MOI.get(nlp_model, DiffOpt.ForwardVariablePrimal(), x)
dy_dx = MOI.get(nlp_model, DiffOpt.ForwardVariablePrimal(), y)
```

#### Reverse Differentiation
```julia
# Reverse differentiation
DiffOpt.reverse_differentiate!(nlp_model)

# Retrieve reverse sensitivities (example usage)
dparam_dx = MOI.get(nlp_model, DiffOpt.ReverseObjectiveFunction())
```

### 🚧 TODO
- [x] **Forward Differentiation**: Implemented and validated for custom primal and dual variables.
- [ ] **Reverse Differentiation**: Implemented to compute transpose Jacobian products.
- [ ] **Tests**: Add comprehensive test cases for forward and reverse differentiation.
- [ ] **Documentation**: Extend user documentation with more examples and edge case scenarios.

### 🛠 Future Work
- Allow different methods to factorize the "M" matrix and solve the linear system of equations needed.

2025-01-04 13:20 UTC, frapac reviewed
good job @andrewrosemberg ! I appreciate the numerous unit-tests you have shipped with this PR. 

I will try to run your code locally on small NLP instances, to assess how fast is the current implementation (my main concern is the total number of allocations). I will try also to test your code on parameterized OPF instances, to assess how far we can get in term of size.

2025-01-04 13:20 UTC, frapac commented on test/data/nlp_problems.jl
> +From sIpopt paper: https://optimization-online.org/2011/04/3008/
very nice!

2025-01-04 13:20 UTC, frapac commented on src/NonLinearProgram/nlp_utilities.jl
> +    ret = H + H'
Do we assume `H` is lower-triangular?

2025-01-04 13:20 UTC, frapac commented on src/NonLinearProgram/nlp_utilities.jl
> +function fill_off_diagonal(H)
Maybe constrain the input type? `H::SparseMatrixCSC`

2025-01-04 13:20 UTC, frapac commented on src/NonLinearProgram/nlp_utilities.jl
> +    y = [model.y[model.model.nlp_index_2_constraint[row].value] for row in rows]
Is there a proper getter to access `model.model.nlp_index_2_constraint`?

2025-01-04 13:20 UTC, frapac commented on src/NonLinearProgram/nlp_utilities.jl
> +    # The signals are being sdjusted to match the Ipopt convention (inner.mult_g)
`sdjusted` => `adjusted`

2025-01-04 13:20 UTC, frapac commented on src/NonLinearProgram/nlp_utilities.jl
> +Compute the optimal Hessian of the Lagrangian and Jacobian of the constraints.
What is the "optimal` Hessian? Do you mean the Hessian evaluated at the solution?

2025-01-04 13:20 UTC, frapac commented on src/NonLinearProgram/nlp_utilities.jl
> +    find_inequealities(cons::Vector{JuMP.ConstraintRef})
`find_inequealities` => `find_inequalities`

2025-01-04 13:20 UTC, frapac commented on src/NonLinearProgram/nlp_utilities.jl
> +    findall(x -> x == 1, geq_locations)
I would put the two `findall`on the same line

2025-01-04 13:20 UTC, frapac commented on src/NonLinearProgram/nlp_utilities.jl
> +    return X,
I would maybe do a pass of JuliaFormatters there

2025-01-04 13:20 UTC, frapac commented on src/NonLinearProgram/nlp_utilities.jl
> +    build_M_N(model::Model, cons::Vector{MOI.Nonlinear.ConstraintIndex}, _X::AbstractVector, _V_L::AbstractVector, _X_L::AbstractVector, _V_U::AbstractVector, _X_U::AbstractVector, leq_locations::Vec
How about renaming this function `build_sensitivity_matrices` ?

2025-01-04 13:20 UTC, frapac commented on src/NonLinearProgram/nlp_utilities.jl
> +    # M matrix
Comment is appreciated!

2025-01-04 13:20 UTC, frapac commented on src/NonLinearProgram/nlp_utilities.jl
> +    M = spzeros(
I think there should be a cleaner way to build `M` and `N`, with less allocations. Let me try to build a MWE, we can assess later if we should address this in this PR or later.

2025-01-04 13:20 UTC, frapac commented on src/NonLinearProgram/nlp_utilities.jl
> +Inertia correction for the factorization of the KKT matrix. Sparse version.
The theoretical question is: do we need to run inertia correction at the optimum? It could be necessary if SOSC is not satisfied at the solution indeed, but in that case I am not sure the sIpopt's formula remains valid.

2025-01-04 13:20 UTC, frapac commented on src/NonLinearProgram/nlp_utilities.jl
> +    # Sesitivity of the solution (primal-dual_constraints-dual_bounds) w.r.t. the parameters
`Sesitivity` => `Sensitivity`

2025-01-04 13:20 UTC, frapac commented on src/NonLinearProgram/nlp_utilities.jl
> +    ∂s = -∂s
Maybe we should add a comment to explain why we are multiplying by `-1` there

2025-01-06 16:59 UTC, andrewrosemberg commented on src/NonLinearProgram/nlp_utilities.jl
> +    y = [model.y[model.model.nlp_index_2_constraint[row].value] for row in rows]
Not that I know of. @joaquimg , do you ?

2025-01-06 17:01 UTC, andrewrosemberg commented on src/NonLinearProgram/nlp_utilities.jl
> +Compute the optimal Hessian of the Lagrangian and Jacobian of the constraints.
yes, will edit!

2025-01-06 17:04 UTC, andrewrosemberg commented on src/NonLinearProgram/nlp_utilities.jl
> +    findall(x -> x == 1, geq_locations)
This was made by formatter. I believe we need it to pass the format test

2025-01-06 17:04 UTC, andrewrosemberg commented on src/NonLinearProgram/nlp_utilities.jl
> +    return X,
I did, this was all done by formatter

2025-01-06 17:22 UTC, andrewrosemberg commented on src/NonLinearProgram/nlp_utilities.jl
> +Inertia correction for the factorization of the KKT matrix. Sparse version.
I think you are right, but couldn't there be numerical errors? 

Moreover, I believe the rest of DiffOpt just assumes that the necessary conditions hold (even if they don't). The thing is that their method doesn't fail when it doesn't hold, while sIpopt method appears to throw singular matrix error when either the conditions don't hold or when we have numerical errors. Therefore, I tried to make it consistent.

2025-01-08 18:44 UTC, frapac commented
@andrewrosemberg Playing with your branch right now, I must say I like DiffOpt's interface! 

I did a dummy mistake when solving the problem HS15 and retrieving the sensitivity. A MWE is: 

```julia
model = Model(() -> DiffOpt.diff_optimizer(Ipopt.Optimizer))
@variable(model, p[1:2] ∈ MOI.Parameter.([100.0, 1.0]))
@variable(model, x[1:2])
set_upper_bound.(x[1], 0.5)
@objective(model, Min, p[1] * (x[2] - x[1]^2)^2 +  (p[2] - x[1])^2)
@constraint(model, x[1] * x[2] >= 1.0)
@constraint(model, x[1] + x[2]^2 >= 0.0)

optimize!(model)
# set parameter pertubations
MOI.set(model, DiffOpt.ForwardParameter(), p[1], 1.0)

# # forward differentiate
DiffOpt.forward_differentiate!(model)

Δx = [
    MOI.get(model, DiffOpt.ForwardVariablePrimal(), var) for
    var in x
]

```

I forgot to specify the sensitivity for `p[2]`, resulting in an error. I am wondering what would be the expected behavior here:
- by default, should we set the sensitivity to `0.0` ? 
- or should we raise a proper error message if the user has forgotten to specify some sensitivities?

2025-01-08 19:36 UTC, Robbybp commented on src/NonLinearProgram/nlp_utilities.jl
> +Inertia correction for the factorization of the KKT matrix. Sparse version.
Maybe we should log a warning if inertia correction is necessary (apologies if you're already doing this) or add an option `allow_intertia_correction` that defaults to true?

2025-01-08 20:01 UTC, frapac commented
Also, if I query the solution after calling `forward_differentiate` I get an error. Is this expected? 

The MWE is: 
```julia
model = Model(() -> DiffOpt.diff_optimizer(Ipopt.Optimizer))
@variable(model, p[1:2] ∈ MOI.Parameter.([100.0, 1.0]))
@variable(model, x[1:2])
set_upper_bound.(x[1], 0.5)
@objective(model, Min, p[1] * (x[2] - x[1]^2)^2 +  (p[2] - x[1])^2)
@constraint(model, x[1] * x[2] >= 1.0)
@constraint(model, x[1] + x[2]^2 >= 0.0)
optimize!(model)
# set parameter pertubations
MOI.set(model, DiffOpt.ForwardParameter(), p[1], 1.0)
MOI.set(model, DiffOpt.ForwardParameter(), p[2], 1.0)

# # forward differentiate
DiffOpt.forward_differentiate!(model)

JuMP.value.(x)

```

Output: 
```
┌ Warning: The model has been modified since the last call to `optimize!` (or `optimize!` has not been called yet). If you are iteratively querying solution information and modifying a model, query all the results first, then modify the model.
└ @ JuMP ~/.julia/packages/JuMP/CU7H5/src/optimizer_interface.jl:1085
ERROR: LoadError: OptimizeNotCalled()
```

2025-01-08 22:17 UTC, andrewrosemberg commented
> I forgot to specify the sensitivity for `p[2]`, resulting in an error. I am wondering what would be the expected behavior here:
> 
> * by default, should we set the sensitivity to `0.0` ?
> * or should we raise a proper error message if the user has forgotten to specify some sensitivities?

@frapac good question! I am fine either way. @joaquimg what would be the consistent approach given the rest of DIffOpt?

2025-01-08 22:23 UTC, andrewrosemberg commented
> Also, if I query the solution after calling forward_differentiate I get an error. Is this expected?

I don't think this is the desired outcome haha Not sure how to ask MOI to ignore the forward attributes, but I will look into it.  @joaquimg do you have an idea on how to avoid this?

2025-01-09 07:15 UTC, frapac commented
@andrewrosemberg Another issue I noted: if we are using non-standard indexing in JuMP (`DenseAxisArray` instead of `Vector{VariableRef}`) I got an error when retrieving the sensitivity 

```
ERROR: LoadError: MethodError: no method matching similar(::Type{Vector{Float64}}, ::Tuple{UnitRange{Int64}})
The function `similar` exists, but no method is defined for this combination of argument types.
```

A MWE is:

```julia
model = Model(() -> DiffOpt.diff_optimizer(Ipopt.Optimizer))
@variable(model, p[1:2] ∈ MOI.Parameter.([100.0, 1.0]))
# N.B: use non-standard indexing
@variable(model, x[0:2])
set_upper_bound.(x[1], 0.5)
@objective(model, Min, p[1] * (x[2] - x[1]^2)^2 +  (p[2] - x[1])^2)
@constraint(model, x[1] * x[2] >= 1.0)
@constraint(model, x[1] + x[2]^2 >= 0.0)
optimize!(model)
# set parameter pertubations
MOI.set(model, DiffOpt.ForwardParameter(), p[1], 1.0)
MOI.set(model, DiffOpt.ForwardParameter(), p[2], 1.0)

# # forward differentiate
DiffOpt.forward_differentiate!(model)

Δx = [
    MOI.get(model, DiffOpt.ForwardVariablePrimal(), var) for
    var in x
]


```

2025-01-09 07:24 UTC, frapac commented
Pushing it one step further, I have tried to differentiate an ACOPF instance using DiffOpt. I re-used the code in rosetta-opf, and ported it to DiffOpt. You can find a gist [here](https://gist.github.com/frapac/2e81f6c61661effdce0d8b78f52995b0). 

Two observations: 
- on `case9`, DiffOpt is using inertia correction. This is not expected, as I am sure we satisfy all the good constraints qualifications in `case9`. I am not sure to understand why UMFPACK fails to factorize the KKT system. 
- on `case1354pegase`, I get an out-of-memory error. This is caused by [this line](https://github.com/andrewrosemberg/DiffOpt.jl/blob/ar/NonLinearProgram/src/NonLinearProgram/nlp_utilities.jl#L415), which allocates a dense matrix.

2025-02-05 17:07 UTC, andrewrosemberg commented on src/NonLinearProgram/nlp_utilities.jl
> +Inertia correction for the factorization of the KKT matrix. Sparse version.
done!

2025-02-05 17:22 UTC, andrewrosemberg commented
> @andrewrosemberg Another issue I noted: if we are using non-standard indexing in JuMP (`DenseAxisArray` instead of `Vector{VariableRef}`) I got an error when retrieving the sensitivity
> 
> ```
> ERROR: LoadError: MethodError: no method matching similar(::Type{Vector{Float64}}, ::Tuple{UnitRange{Int64}})
> The function `similar` exists, but no method is defined for this combination of argument types.
> ```
> 
> A MWE is:

> Δx = [
>     MOI.get(model, DiffOpt.ForwardVariablePrimal(), var) for
>     var in x
> ]
> ```

I believe that is a Julia thing. If you try the same with `value(var)` it will give a similar error. if you iterate by index it works.

2025-02-05 18:45 UTC, andrewrosemberg commented on src/NonLinearProgram/nlp_utilities.jl
> +    ret = H + H'
I was following Oscar's steps from here: 

https://github.com/jump-dev/JuMP.jl/blob/54c1239ee964b13012a4553b4e36bfb5579e6aff/docs/src/tutorials/nonlinear/querying_hessians.jl#L204-L221

2025-02-05 18:45 UTC, andrewrosemberg commented on src/NonLinearProgram/nlp_utilities.jl
> +function fill_off_diagonal(H)
done!

2025-02-07 00:23 UTC, andrewrosemberg commented
> I forgot to specify the sensitivity for `p[2]`, resulting in an error. I am wondering what would be the expected behavior here:
> 
> * by default, should we set the sensitivity to `0.0` ?
> * or should we raise a proper error message if the user has forgotten to specify some sensitivities?

@frapac I have just set the sensitivities to zero since it seems to be the way that we went in the parametric interface Joaquim did.

2025-02-13 20:16 UTC, andrewrosemberg commented
> * on `case9`, DiffOpt is using inertia correction. This is not expected, as I am sure we satisfy all the good constraints qualifications in `case9`. I am not sure to understand why UMFPACK fails to factorize the KKT system.

@frapac , this happens because of the following constraints:

```
JuMP.@constraint(model, branch["angmin"] <= va_fr - va_to <= branch["angmax"])
```

This creates two linearly dependent constraints. Ipopt and sipopt avoid any problems by eliminating the non-active constraint. Currently, our method uses the full KKT. This is very suboptimal but changing requires some careful steps. I will create an Issue to record this but I believe it should be solved in a subsequent PR.

2025-02-13 20:25 UTC, andrewrosemberg commented
> * on `case1354pegase`, I get an out-of-memory error. This is caused by [this line](https://github.com/andrewrosemberg/DiffOpt.jl/blob/ar/NonLinearProgram/src/NonLinearProgram/nlp_utilities.jl#L415), which allocates a dense matrix. I would suggest replacing `diagm` by `SparseArrays.spdiagm`

@frapac this is now fixed, thank you :)

2025-02-16 06:56 UTC, joaquimg requested changes
First pass

2025-02-16 06:56 UTC, joaquimg commented on docs/src/manual.md
> +|    `ScalarNonlinearFunction`    |    `EqualTo`    |
this section is about the QP backend, we need a separate section for the NLP backend

2025-02-16 06:56 UTC, joaquimg commented on docs/src/manual.md
> +| `ScalarNonlinearFunction`  |
same as above

2025-02-16 06:56 UTC, joaquimg commented on docs/src/usage.md
> +@objective(model, Min, 2x)
lets do somethinf slightly nl like x^4

2025-02-16 06:56 UTC, joaquimg commented on docs/src/usage.md
> +3. To differentiate a general nonlinear program, have to use the API for Parameterized JuMP models. For example, consider the following nonlinear program:
In forward mode,
what happens in the NLP backend if one tries to Set something other than parameters?

In reverse mode, 
what happens in the NLP backend if one tries to Get something other than parameters?

Are these cases tested?

2025-02-16 06:56 UTC, joaquimg commented on src/parameters.jl
> +
doesnt it exist already?
https://github.com/jump-dev/DiffOpt.jl/blob/95927fae094da6603cfe02f608d7bf92898bb70d/src/parameters.jl#L307

2025-02-16 06:56 UTC, joaquimg commented on src/diff_opt.jl
> +struct ForwardConstraintDual <: MOI.AbstractConstraintAttribute end
creat issue to allow using this in other modes

2025-02-16 06:56 UTC, joaquimg commented on src/diff_opt.jl
> +    reverse_differentiate!(model::MOI.ModelLike; kwargs...)
docs for kwargs?

2025-02-16 06:56 UTC, joaquimg commented on src/diff_opt.jl
> +    dy::Dict{MOI.ConstraintIndex,Float64} = Dict{MOI.ConstraintIndex,Float64}()
add a comment here mentioning it currently only works for NLP

2025-02-16 06:56 UTC, joaquimg commented on src/NonLinearProgram/nlp_utilities.jl
> +    y = [model.y[model.model.nlp_index_2_constraint[row].value] for row in rows]
if there was, it would be a MOI.get...

2025-02-16 06:56 UTC, joaquimg commented on src/NonLinearProgram/nlp_utilities.jl
> +function fill_off_diagonal(H::SparseMatrixCSC)
we need underscores in all non-user facing API functions, e.g. `_fill_off_diagonal`

2025-02-16 06:56 UTC, joaquimg commented on src/NonLinearProgram/nlp_utilities.jl
> +        # dual.(UpperBoundRef(primal_vars[j])) * (- sense_multiplier)
remove?

2025-02-16 06:56 UTC, joaquimg commented on src/NonLinearProgram/nlp_utilities.jl
> +        #dual.(LowerBoundRef(primal_vars[j])) * sense_multiplier
remove?

2025-02-16 06:56 UTC, joaquimg commented on src/NonLinearProgram/nlp_utilities.jl
> +        # dual.(con) * (- sense_multiplier)
remove?

2025-02-16 06:56 UTC, joaquimg commented on src/NonLinearProgram/nlp_utilities.jl
> +Inertia correction for the factorization of the KKT matrix. Sparse version.
inertial correction should be set as a MOI attribute, not as a keyword

2025-02-16 06:56 UTC, joaquimg commented on src/NonLinearProgram/NonLinearProgram.jl
> +function add_leq_geq(form::Form, idx::MOI.ConstraintIndex, set::MOI.GreaterThan)
underscores...

2025-02-16 06:56 UTC, joaquimg commented on src/diff_opt.jl
> +    reverse_differentiate!(model::MOI.ModelLike; kwargs...)
probably should be MOI attributes set on the model, not kwargs

2025-02-16 06:56 UTC, joaquimg commented on src/jump_moi_overloads.jl
> +function reverse_differentiate!(model::JuMP.Model; kwargs...)
avoid kwargs if we can use MOI attributes

2025-02-16 07:00 UTC, joaquimg commented
Also, I dont know why codecov is not showing up...

2025-02-16 20:43 UTC, andrewrosemberg commented on docs/src/usage.md
> +@objective(model, Min, 2x)
done!

2025-02-16 20:44 UTC, andrewrosemberg commented on docs/src/manual.md
> +| `ScalarNonlinearFunction`  |
Good catch. fixed!

2025-02-16 20:44 UTC, andrewrosemberg commented on docs/src/manual.md
> +|    `ScalarNonlinearFunction`    |    `EqualTo`    |
Good catch. fixed!

2025-02-16 20:49 UTC, andrewrosemberg commented on docs/src/usage.md
> +3. To differentiate a general nonlinear program, have to use the API for Parameterized JuMP models. For example, consider the following nonlinear program:
Good point, I have now extended test from Parameter interface for the non POI version.

2025-02-16 20:49 UTC, andrewrosemberg commented on src/diff_opt.jl
> +    dy::Dict{MOI.ConstraintIndex,Float64} = Dict{MOI.ConstraintIndex,Float64}()
done!

2025-02-16 21:13 UTC, joaquimg commented on src/parameters.jl
> +
Oh, fine!

2025-02-17 19:47 UTC, andrewrosemberg commented on src/NonLinearProgram/nlp_utilities.jl
> +        #dual.(LowerBoundRef(primal_vars[j])) * sense_multiplier
done

2025-02-17 19:47 UTC, andrewrosemberg commented on src/NonLinearProgram/nlp_utilities.jl
> +        # dual.(con) * (- sense_multiplier)
done

2025-02-17 19:48 UTC, andrewrosemberg commented on src/NonLinearProgram/NonLinearProgram.jl
> +function add_leq_geq(form::Form, idx::MOI.ConstraintIndex, set::MOI.GreaterThan)
changed!

2025-02-17 21:43 UTC, andrewrosemberg commented on src/jump_moi_overloads.jl
> +function reverse_differentiate!(model::JuMP.Model; kwargs...)
changed to MOI.AbstractModelAttribute

2025-02-18 05:26 UTC, joaquimg requested changes

2025-02-18 05:26 UTC, joaquimg commented on src/NonLinearProgram/NonLinearProgram.jl
> +get_num_params(model::Model) = get_num_params(model.model)
all these might need underscores

2025-02-18 05:26 UTC, joaquimg commented on src/NonLinearProgram/nlp_utilities.jl
> +function fill_off_diagonal(H::SparseMatrixCSC)
underscores?

2025-02-18 05:26 UTC, joaquimg commented on src/NonLinearProgram/nlp_utilities.jl
> +function compute_optimal_hessian(
all these will also need underscores

2025-02-18 05:26 UTC, joaquimg commented on src/NonLinearProgram/nlp_utilities.jl
> +# in the LICENSE.md file or at https://opensource.org/licenses/MIT.
the header should mention the tutorial you got code from

2025-02-18 05:26 UTC, joaquimg commented on src/NonLinearProgram/nlp_utilities.jl
> +    # M matrix
I think @frapac means, add a better comment referencing the paper you got this from?

2025-02-18 05:26 UTC, joaquimg commented on src/diff_opt.jl
> +factorization.
needs comments about the parameters.

we need to think a bit more about this.

Initially I thought about having the parameters st and max corrections as atrrbitues.

Do we expect people will pass their factorization routines?

2025-02-18 05:26 UTC, joaquimg commented on src/diff_opt.jl
> +    reverse_differentiate!(model::MOI.ModelLike; kwargs...)
we need to remove the kwargs

2025-02-18 05:26 UTC, joaquimg commented on src/jump_moi_overloads.jl
> +function reverse_differentiate!(model::JuMP.Model; kwargs...)
remove the kwargs now?

2025-02-18 16:00 UTC, andrewrosemberg commented on src/NonLinearProgram/nlp_utilities.jl
> +# in the LICENSE.md file or at https://opensource.org/licenses/MIT.
done

2025-02-18 16:00 UTC, andrewrosemberg commented on src/NonLinearProgram/NonLinearProgram.jl
> +get_num_params(model::Model) = get_num_params(model.model)
done

2025-02-18 16:01 UTC, andrewrosemberg commented on src/diff_opt.jl
> +factorization.
This allows user to use better factorization routines like the ones in HSL.

2025-02-21 05:07 UTC, joaquimg commented on src/diff_opt.jl
> +struct ForwardConstraintDual <: MOI.AbstractConstraintAttribute end
https://github.com/jump-dev/DiffOpt.jl/issues/94

2025-02-21 06:06 UTC, merged